# question_data = [
# {"text": "A slug's blood is green.", "answer": "True"},
# {"text": "The loudest animal is the African Elephant.", "answer": "False"},
# {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
# {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
# {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
# {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
# {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
# {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
# {"text": "Google was originally called 'Backrub'.", "answer": "True"},
# {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
# {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
# {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]
# https://opentdb.com/api_config.php

question_data = [
        {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "easy",
         "question": "In the &quot;Shrek&quot; film franchise, Donkey is played by Eddie Murphy.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Coca-Cola&#039;s original colour was green.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "There are no roads in\/out of Juneau, Alaska.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "medium",
         "question": "Assyrian king Sennacherib&#039;s destruction of Babylon in 689 BCE was viewed as a triumph by other Assyrian citizens.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Luigi is taller than Mario?", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "The anime &quot;Lucky Star&quot; follows the story of one girl who is unaware she is God.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "The Sun rises from the North.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game&#039;s plot.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
         "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
         "question": "An Astronomical Unit is the distance between Earth and the Moon.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
         "question": "A &#039;Millinillion&#039; is a real number.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Santa Claus&quot; is a variety of melon.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Neutral Milk Hotel&quot; is a real band.", "correct_answer": "True",
         "incorrect_answers": ["False"]}
    ]
